config/routes.rb
Rails.application.routes.draw do

  root to: "public/pages#home"
  
  devise_for :users
  
  devise_scope :user do
    get 'login'  => 'users/sessions#new',     as: "login"  # published url
    get 'logout' => 'users/sessions#destroy', as: "logout" # published url
  end
    
  namespace :public do
    get 'home' => 'pages#home'
    get 'dash' => 'pages#dashboard'
  end
  
  namespace :admin do
    get 'dashboard' => 'dashboard#show'
    resources :jobs
    resources :users
    resources :customers
    resources :consumers
    resources :interpreters
  end
  
  namespace :customer do
    get 'dashboard' => 'dashboard#show'
    resources :jobs
  end
  
  namespace :consumer do
    get 'dashboard' => 'dashboard#show'
    resources :jobs
  end
  
  namespace :interpreter do
    get 'dashboard' => 'dashboard#show'
    resources :jobs
  end
  
end

app/models/customer.rb
class Customer < ActiveRecord::Base
    
  validates :company_name,    :presence => true, uniqueness: true
  validates :requester_name,  :presence => true
  validates :requester_email, :presence => true
  validates :billing_email,   :presence => true
  # billing rate is stored in integer cents (not dollars)  
  validates :billing_rate, numericality: { only_integer: true }
  
  has_one  :address, :as => :addressable
  has_many :phones,  :as => :phoneable
  has_many :jobs
  
  belongs_to :agency
  
  has_many :requesters, foreign_key: "customer_id", class_name: "User"
  
  def to_s
    "<Customer#{id} #{company_name}>"
  end
    
end

app/models/job.rb
class Job < ActiveRecord::Base
    
  validates :status,       :presence => true
  validates :agency_id,    :presence => true
  validates :consumer_id,  :presence => true
  validates :customer_id,  :presence => true
  validates :description,  :presence => true
  validates :starts_at,    :presence => true
  validates :duration,     :presence => true, numericality: { only_integer: true }  
  validates :requested_at, :presence => true
  
  belongs_to :agency
  belongs_to :customer  
  belongs_to :created,     :class_name => "User", :foreign_key => "created_id"
  belongs_to :updated,     :class_name => "User", :foreign_key => "updated_id"
  belongs_to :consumer,    :class_name => "User", :foreign_key => "consumer_id"
  belongs_to :interpreter, :class_name => "User", :foreign_key => "interpreter_id"
  
  scope :open,     -> { where(interpreter_id: nil) }  
  scope :assigned, -> { where.not(interpreter_id: nil) }  

  scope :before, ->(date) { where("starts_at < ?", date.beginning_of_day) }
  scope :after,  ->(date) { where("starts_at > ?", date.end_of_day) }
  scope :on_day, ->(date) { where(starts_at: date.beginning_of_day..date.end_of_day) }
  
  scope :past, -> { before(Time.zone.now.to_date) }
  scope :today, -> { on_day(Time.zone.now.to_date) }
  scope :future, -> { after(Time.zone.now.to_date) }
  
  attr_accessor :duration_string
  
  extend SimpleCalendar
  
  has_calendar
  
  # before_save :clean_up_data
  # def clean_up_data
  #   # strip off any time in the starts_at field
  #   self.starts_at = self.starts_at.to_date
  # end
  
  def state
    return :past  if starts_at.to_date < Time.zone.now.to_date
    return :open unless interpreter
    return :today if starts_at.to_date == Time.zone.now.to_date
    :pending # future
  end    
    
  def when
    date_string = starts_today? ? 'Today' : starts_at.strftime('%-m/%-d')
    "#{date_string} @ #{start_time.strftime('%l:%M %P')} for #{duration_string}"
  end
  
  def starts_today?
    Time.zone.now.to_date == starts_at.to_date
  end
  
  def duration_string
    case duration
      when 60 
        '1 hour'
      when 120
        '2 hours'
      else
        "#{duration} mins"
      end
  end
  
  def to_s
    "<Job#{id} #{description[0..20]}>"
  end
  
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < Admin::BaseController
  
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  def index
    trace "*** Admin::CustomerController#index #{current_agency}"
    @customers = current_agency.customers.to_a
  end

  def show
  end

  def new
    dummy = {
      company_name:    Faker::Company.name,
      requester_name:  Faker::Name.name,
      requester_email: Faker::Internet.email,
      billing_email:   Faker::Internet.email,
      billing_rate:    Faker::Number.number(4) 
    }
    @customer = Customer.new( dummy )
  end

  def edit
  end

  def create
    trace "*** Admin::CustomerController#create #{params}"
    @customer = current_agency.customers.build(customer_params)
    trace "--- new customer = #{@customer}"

    if @customer.save
      trace "--- success #{@customer}"
      redirect_to admin_customer_path(@customer), notice: 'Customer was successfully created.'
    else
      trace "--- failure errors=#{@customer.errors.full_messages}"
      render :new
    end
  end

  def update
    trace "*** Admin::CustomerController#update customer_params = #{customer_params}"
    if @customer.update(customer_params)
      trace "--- success #{@customer.inspect}"
      redirect_to admin_customer_path(@customer), notice: 'Customer was successfully updated.'
    else
      trace "--- failure errors=#{@customer.errors.full_messages}"
      render :edit
    end
  end

  def destroy
    @customer.destroy
    redirect_to admin_customers_url, notice: 'Customer was successfully destroyed.'
  end

  private  
  
  def set_customer
    @customer = current_agency.customers.find(params[:id])
  end

  def customer_params
    params.require(:customer).permit(:company_name, :requester_name, :requester_email, :billing_email, :billing_rate)
  end
  
end

app/controllers/admin/jobs_controller.rb
class Admin::JobsController < Admin::BaseController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  def index
    @jobs = current_agency.jobs.order('created_at DESC').all
  end

  def show
  end

  def new
    agency = current_agency
    now = Time.zone.now.to_date
    trace "*** now = #{now}"
    @job = Job.new({
      agency_id: agency.id,
      customer: agency.customers.first,
      consumer_id: agency.consumers.last.id,
      interpreter_id: agency.interpreters.first.id,
      start_time: Time.parse("1:00pm"),
      starts_at: now
    })
  end

  def edit
  end

  def create
    trace "*** JobsController#create params = #{params}"
    convert_date('starts_at') # changes the params
    trace "--- job params = #{job_params}"
    @job = Job.new(job_params.merge(agency: current_agency))
    @job.repeats = @job.repeat_style != 'None'
    @job.requested_at = Time.zone.now
    @job.created_id = current_user.id
    @job.updated_id = current_user.id
    @job.status ||= 'Active'
    if @job.save
      redirect_to admin_job_path(@job), notice: 'Job was successfully created.'
    else
      render :new
    end
  end

  def update
    trace "*** JobsController#update job params = #{job_params}"
    convert_date('starts_at') # changes the params
    trace "--- job params = #{job_params}"
    @job.updated_id = current_user.id
    if @job.update(job_params)
      redirect_to admin_job_path(@job), notice: 'Job was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @job.destroy
    redirect_to admin_jobs_url, notice: 'Job was successfully destroyed.'
  end

  private
   
  def set_job
    @job = current_agency.jobs.find(params[:id])
  end

  def job_params
    params.require(:job).permit(:description, :consumer_id, :customer_id, :interpreter_id,
    :starts_at, :start_time, :duration, :ends_on, :repeats, :repeat_style, :repeat_pattern )
  end
  
end

app/controllers/customer/base_controller.rb
class Customer::BaseController < ApplicationController
      
  before_action :authenticate_customer!
  before_action :set_globals
  
  helper_method :current_customer
  def current_customer
    current_user.try(:customer)
  end

private

  def set_globals
    @dashboard_path = customer_dashboard_path
    @header_partial = 'partials/header/header_customer'
  end

  def authenticate_customer!
    # trace "authenticate_admin! current_user=#{current_user}"
    redirect_to root_path unless current_user.requester?
  end
  
  def after_sign_in_path_for(resource)
    customer_dashboard_path if resource.try(:requester?)
  end

end

app/controllers/customer/dashboard_controller.rb
class Customer::DashboardController < Customer::BaseController
    
  def show
    @jobs = current_user.customer.jobs
    # today = Time.zone.now.to_date
    # @past_jobs   = @jobs.after(today)
    # @today_jobs  = @jobs.on_day(today)
    # @future_jobs = @jobs.before(today)
  end
   
end

app/controllers/customer/jobs_controller.rb
class Customer::JobsController < Customer::BaseController
  
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  def index
    @jobs = current_user.customer.jobs.order('starts_at ASC').all
  end

  def show
  end
  
  def edit
  end
  
  def new
    @job = Job.new({
      agency_id: current_agency.id,
      customer: current_customer,
      consumer_id: current_agency.consumers.last.id,
      description: Faker::Lorem.sentence([4,5,6].sample),
      start_time: Time.parse("1:00pm"),
      starts_at: Time.zone.now.to_date
    })
  end  

  def create
    trace "*** Customer::JobsController#create params = #{params}"
    trace "--- current agency = #{current_agency}"
    convert_date('starts_at') # changes the params
    trace "--- job params = #{job_params}"
    @job = Job.new(job_params.merge(agency: current_agency,customer: current_customer))
    @job.repeats = @job.repeat_style != 'None'
    @job.requested_at = Time.zone.now
    @job.created_id = current_user.id
    @job.updated_id = current_user.id
    @job.status ||= 'Pending'
    if @job.save
      redirect_to customer_job_path(@job), notice: 'Job was successfully created.'
    else
      trace "--- create failed. errors = #{@job.errors.full_messages}"
      render :new
    end
  end

  def update
    trace "*** Customer::JobsController#update job params = #{job_params}"
    convert_date('starts_at') # changes the params
    trace "--- job params = #{job_params}"
    @job.updated_id = current_user.id
    if @job.update(job_params)
      redirect_to customer_job_path(@job), notice: 'Job was successfully updated.'
    else
      trace "--- update failed. errors = #{@job.errors.full_messages}"
      render :edit
    end
  end

  def destroy
    @job.destroy
    redirect_to customer_jobs_url, notice: 'Job was successfully destroyed.'
  end
  
  private
    
  def set_job
    @job = current_agency.jobs.find(params[:id])
  end

  def job_params
    params.require(:job).permit(:description, :consumer_id,
    :starts_at, :start_time, :duration, :ends_on, :repeats, :repeat_style, :repeat_pattern )
  end
  
end

app/controllers/interpreter/jobs_controller.rb
class Interpreter::JobsController < Interpreter::BaseController
  
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  def index
    @jobs = current_user.interpreter_jobs.order('starts_at ASC').all
    # today = Time.zone.now.to_date
    # @past_jobs = current_user.interpreter_jobs.before(today).assigned
    # @today_jobs = current_user.interpreter_jobs.on_day(today).assigned
    # @future_jobs = current_user.interpreter_jobs.after(today).assigned
    @open_jobs = current_agency.jobs.open
  end

  def show
  end

  private
  
  def convert_date(field)
    date_string = job_params[field] # '05/25/2015'
    date_value = Date.strptime(date_string,"%m/%d/%Y") 
    params['job'][field] = date_value.strftime('%Y-%m-%d')    
  end
  
  def set_job
    @job = current_agency.jobs.find(params[:id])
  end

  def job_params
    params.require(:job).permit(:description, :consumer_id, :customer_id, :interpreter_id,
    :starts_at, :start_time, :duration, :ends_on, :repeats, :repeat_style, :repeat_pattern )
  end
  
end

app/views/customer/jobs/_form.html.erb
<%= simple_form_for([:customer,@job]) do |f| %>

  <%= render 'partials/model_errors', resource: @job %>

  <%= f.label :on %>
  <input type="text" id='job_starts_at' name='job[starts_at]' value='<%= @job.starts_at.to_date.strftime('%-m/%-d/%y') %>'>
  <br>

  <%= f.label :at %>
  <div class='input-append bootstrap-datepicker-component' style='display: inline;'>
	  <input class='dateselect-time input-small' name='job[start_time]' type='text' value='1:00 PM'>
  </div>
  <br>

  <%= f.label :for %>
  <%= f.input_field :duration, collection: ['30', '60', '90', '120', '360'], include_blank: false %> mins duration
  <br>

  <%= f.label :repeats %>
  <%= f.input_field :repeat_style, collection: ['None', 'Monthly', 'Weekly', 'Weekdays', 'Daily'], include_blank: false %>
  <br>

  <%= f.label :until %>
  <input type="text" id='job_ends_on' name='job[ends_on]' data-provide='datepicker' >
  <br>

  <%= f.label :description %>
  <%= f.input_field :description, style:"width: 400px !important;" %>
  <br>

  <%= f.label :consumer %>
  <%= f.input_field :consumer, collection: @job.agency.consumers, name:'job[consumer_id]', label_method: :fullname, include_blank: false %>
  <br>

  <%= f.button :submit, class: 'button-create' %>

<% end %>

<script type="text/javascript">
  $('#job_starts_at').datepicker({
	format: 'mm/dd/yy',
    startDate: '+1d'  
  });
  $('.dateselect-time').timepicker({
      minuteStep: 15,
      showInputs: true,
      disableFocus: true
  });
</script>

app/views/customer/jobs/_job_actions.html.erb
<h3>Your Jobs</h3>
<div class="table-responsive">
<table class="table">
  <thead>
    <tr>
      <th>Job#</th>
      <th>State</th>
	  <th>Consumer</th>
	  <th>Interpreter</th>
      <th>When</th>
      <th>Description</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @jobs.on_day(Time.zone.now).each do |job| %>
      <tr>
        <td><%= job.id %></td>
        <td><%= job.state.to_s.capitalize %></td>
		<td><%= job.consumer.try(:fullname) %></td>
		<td><%= job.interpreter ? job.interpreter.email : '<<unassigned>>' %></td>
        <td><%= job.when %></td>
        <td><%= job.description %></td>
        <td><%= link_to 'Edit', '#', class: 'button-edit' %></td>
      </tr>
    <% end %>
    <% future_jobs = @jobs.after(Time.zone.now) %>
    <% future_jobs.take(5).each do |job| %>
      <tr>
        <td><%= job.id %></td>
        <td><%= job.state.to_s.capitalize %></td>
		<td><%= job.consumer.try(:fullname) %></td>
		<td><%= job.interpreter ? job.interpreter.email : '<<unassigned>>' %></td>
        <td><%= job.when %></td>
        <td><%= job.description %></td>
        <td><%= link_to 'Details', customer_job_path(job), class: 'button-edit' %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'More Future Jobs...', '#' if future_jobs.count > 5 %>

app/views/customer/jobs/_job_month.html.erb
<h3>Jobs (Month View)</h3>
<div class='calendar job-calendar'>
<%= month_calendar events: @jobs do |date,jobs| %>
	<%= date.strftime("%-d") %>
	<% jobs.take(5).each do |job| %>
		<div><%= link_to "#{job.state}##{job.id}", interpreter_job_path(job) %></div>
  	<% end %>
	<% if jobs.count > 5 %>
		More...
	<% end %>
<% end %>
</div>

app/views/customer/jobs/edit.html.erb
<h1>Edit Job</h1>

<%= render 'form' %>

<%= link_to 'Go to Job Details', admin_job_path(@job) %> |
<%= link_to 'Go to Jobs List', admin_jobs_path %>

app/views/customer/jobs/index.html.erb
<%= render 'job_actions' %>

<%= link_to 'Request a New Job', new_customer_job_path, class: 'button-create' %>

<%= render 'job_month'  %>

app/views/customer/jobs/new.html.erb
<h1>Request a Job</h1>

<%= render 'form' %>

<%= link_to 'Back to List of Jobs', admin_jobs_path %>

app/views/customer/jobs/show.html.erb
<h2>Job#<%= @job.id %></h2>

<div class="row">
	<div class="col-md-6">
		<div class="panel panel-default">
		  <div class="panel-heading">Details</div>
		  <div class="panel-body">
			<p><strong>Consumer   : </strong><%= @job.consumer.try(:fullname) %></p>
			<p><strong>Description: </strong><%= @job.description %></p>
			<p><strong>When       : </strong><%= @job.when %></p>
			<p><strong>Notes      : </strong></p>
			<% if @job.repeats %>
				<p><strong>Repeat Style: </strong><%= @job.repeat_style %></p>
				<p><strong>Repeat Pattern: </strong><%= @job.repeat_pattern %></p>
				<p><strong>Ends On: </strong><%= @job.ends_on.strftime('%Y-%m-%d')  if @job.ends_on %></p>
			<% end %>
		  </div>
		</div>		
	</div>
	<div class="col-md-6">
		<div class="panel panel-default">
		  <div class="panel-heading">Requester</div>
		  <div class="panel-body">
			<p><span class="glyphicon glyphicon-calendar" aria-hidden="true">&nbsp;</span><%= @job.requested_at.strftime('%Y-%m-%d %H:%M') %></p>
			<p><span class="glyphicon glyphicon-user"     aria-hidden="true">&nbsp;</span><%= @job.requested_by_name %></p>
			<p><span class="glyphicon glyphicon-envelope" aria-hidden="true">&nbsp;</span><%= @job.requested_by_email %></p>
			<p><span class="glyphicon glyphicon-phone"    aria-hidden="true">&nbsp;</span><%= @job.requested_by_phone %></p>
		  </div>
		</div>	
	</div>
</div>
<div class="row">
	<div class="col-md-6">
		<div class="panel panel-default">
		  <div class="panel-heading">Interpreter</div>
		  <div class="panel-body">
			<% if @job.interpreter %>
				<p><strong>Email: </strong><%= @job.interpreter.email %></p>
				<p><strong>Rate : </strong><%= format_as_dollars(@job.interpreter.default_payrate) %></p>
			<% else %>
				No Interpreter Assigned
			<% end %>
		  </div>
		</div>
	</div>
	<div class="col-md-6">
		<div class="panel panel-default">
		  <div class="panel-heading">Extra Panel???</div>
		  <div class="panel-body">
		  </div>
		</div>
	</div>
</div>

<%= link_to 'Edit This Job...', edit_customer_job_path(@job) %> |
<%= link_to 'Go to Jobs List...', customer_jobs_path %>