config/routes.rb
Rails.application.routes.draw do

  root to: "public/pages#home"
  
  devise_for :users
  
  devise_scope :user do
    get 'login'  => 'users/sessions#new',     as: "login"  # published url
    get 'logout' => 'users/sessions#destroy', as: "logout" # published url
  end
    
  namespace :public do
    get 'home' => 'pages#home'
    get 'dash' => 'pages#dashboard'
  end
  
  namespace :admin do
    get 'dashboard' => 'dashboard#show'
    resources :jobs
    resources :users
    resources :customers
    resources :consumers
    resources :interpreters
  end
  
  namespace :customer do
    get 'dashboard' => 'dashboard#show'
    resources :jobs
  end
  
  namespace :consumer do
    get 'dashboard' => 'dashboard#show'
    resources :jobs
  end
  
  namespace :interpreter do
    get 'dashboard' => 'dashboard#show'
    resources :jobs
  end
  
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::BaseController
    
  def show
    @jobs = current_agency.jobs
    @customers = current_agency.customers
    @consumers = current_agency.consumers
    @interpreters = current_agency.interpreters
  end
   
end

app/controllers/customer/dashboard_controller.rb
class Customer::DashboardController < Customer::BaseController
    
  def show
    @jobs = current_user.customer.jobs
    # today = Time.zone.now.to_date
    # @past_jobs   = @jobs.after(today)
    # @today_jobs  = @jobs.on_day(today)
    # @future_jobs = @jobs.before(today)
  end
   
end

app/controllers/interpreter/dashboard_controller.rb
class Interpreter::DashboardController < Interpreter::BaseController
    
  def show
    @jobs = current_user.interpreter_jobs
    today = Time.zone.now.to_date
    @past_jobs   = @jobs.after(today)
    @today_jobs  = @jobs.on_day(today)
    @future_jobs = @jobs.before(today)
  end
   
end

app/views/admin/dashboard/show.html.erb
<h1>Dashboard (admin)</h1>

<div class='row'>
	<div class="col-md-4">
		<div class="panel panel-primary">
		  <div class="panel-heading">
		    <h3 class="panel-title">Jobs</h3>
		  </div>
			<div class="panel-body">
				<div class='calendar mini-calendar'>
					<%= month_calendar events: @jobs do |date,jobs| %>
						<strong><%= date.strftime("%-d") %></strong>
						<% if jobs.count > 0 %>
							<p><%= pluralize(jobs.count, 'Job')%></p>
						<% end %>
					<% end %>
				</div>
			</div>
			<div class="panel-footer"><%= "#{@jobs.count} Total Jobs" %></div>
		</div>
	</div>
	<div class="col-md-4">
		<div class="panel panel-primary">
		  <div class="panel-heading">
		    <h3 class="panel-title">Elements</h3>
		  </div>
			<div class="panel-body">
				<p><%= link_to "#{@consumers.count} Consumers...", admin_consumers_path %></p>
				<p><%= link_to "XX Requesters...", '#' %></p>
				<p><%= link_to "#{@customers.count} Customers...", admin_customers_path %></p>
				<p><%= link_to "#{@interpreters.count} Interpreters...", admin_interpreters_path %></p>
			</div>
			<div class="panel-footer">Panel footer</div>
		</div>
	</div>
	<div class="col-md-4">
		<div class="panel panel-primary">
		  <div class="panel-heading">
		    <h3 class="panel-title">Accounting</h3>
		  </div>
			<div class="panel-body">
				<p><%= link_to "Invoices...", '#' %></p>
				<p><%= link_to "Payroll...", '#' %></p>
			</div>
			<div class="panel-footer">Panel footer</div>
		</div>
	</div>	
</div>
<div class='row'>
	<br>
	<div class="panel panel-default">
		<div class="panel-heading">
		    <h3 class="panel-title">Quick Actions</h3>
		</div>
		<div class="panel-body">
			<%= link_to 'Schedule a New Job', new_admin_job_path(:admin), class: 'button-create' %>
			<%= link_to 'Register a New Interpreter', new_admin_interpreter_path, class: 'button-create' %>
		</div>
	</div>
</div>

<script>
$('.day').click( function(event) {
  var clicked_div = $(this);
  console.log('clicked a day')
});
</script>