config/routes.rb
Rails.application.routes.draw do

  root to: "public/pages#home"
  
  devise_for :users
  
  devise_scope :user do
    get 'login'  => 'users/sessions#new',     as: "login"  # published url
    get 'logout' => 'users/sessions#destroy', as: "logout" # published url
  end
    
  namespace :public do
    get 'home' => 'pages#home'
    get 'dash' => 'pages#dashboard'
  end
  
  namespace :admin do
    get 'dashboard' => 'dashboard#show'
    resources :jobs
    resources :users
    resources :customers
    resources :consumers
    resources :interpreters
  end
  
  namespace :customer do
    get 'dashboard' => 'dashboard#show'
    resources :jobs
  end
  
  namespace :consumer do
    get 'dashboard' => 'dashboard#show'
    resources :jobs
  end
  
  namespace :interpreter do
    get 'dashboard' => 'dashboard#show'
    resources :jobs
  end
  
end

app/controllers/admin/consumers_controller.rb
class Admin::ConsumersController < Admin::BaseController
    
  before_action :set_consumer, only: [:show, :edit, :update, :destroy]

  def index
    @consumers = current_agency.consumers.order('created_at DESC').all
  end

  def show
  end

  def new
    name = "test#{rand(1000000)}" # test data
    last = Faker::Name.last_name
    first = Faker::Name.first_name
    @consumer = User.new(last_name: last, first_name: first, 
      default_payrate: 3500, roles: [:consumer], 
      username: name, email: "#{name}@consumer.com")
  end

  def edit
  end

  def create
    trace "*** ConsumersController#create #{params}"
    @consumer = User.create(user_params.merge(agency: current_agency, roles: [:consumer]))
    if @consumer.save
      redirect_to admin_consumer_path(@consumer), notice: 'Consumer was successfully created.'
    else
      trace "--- user save failed, errors = #{@consumer.errors.full_messages}"
      render :new
    end
  end

  def update
    trace "*** ConsumersController#update #{params}"
    # only pass the password to update if user entered one so delete
    params[:user].delete(:password) if params[:user][:password] == ''
    if @consumer.update(user_params)
      redirect_to admin_consumer_path(@consumer), notice: 'Consumer was successfully updated.'
    else
      trace "--- user save failed, errors = #{@consumer.errors.full_messages}"
      render :edit
    end
  end

  def destroy
    @consumer.destroy
    redirect_to admin_consumers_url, notice: 'Consumer was successfully destroyed.'
  end

  private
  
  def set_consumer
    @consumer = current_agency.consumers.find(params[:id])
  end
  
  def user_params
    params.require(:user).permit(:username,:email,:password,:last_name,:first_name,:default_payrate)
  end
    
end

app/views/admin/consumers/edit.html.erb
<h1>Edit Consumer</h1>

<%= simple_form_for(@consumer, :url => { :controller => "consumers", :action => "update" },) do |f| %>
  <%= render 'partials/model_errors', resource: @consumer %>
  <%= f.input :username %>
  <%= f.input :email %>
  <%= f.input :password %>
  <%= f.input :last_name %>
  <%= f.input :first_name %>
  <%= f.button :submit, class: 'button-create' %>
<% end %>

<%= link_to 'Show Consumer Details', admin_consumer_path(@consumer) %> |
<%= link_to 'Go to Consumers List', admin_consumers_path %>

app/views/admin/consumers/index.html.erb
<h1>Consumers</h1>

<table class="table table-hover">  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Jobs</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @consumers.each do |consumer| %>
      <tr>
        <td><%= consumer.id %></td>
        <td><%= consumer.fullname %></td>
        <td><%= consumer.consumer_jobs.count %></td>
        <td><%= consumer.email %></td>
        <td><%= link_to 'Show', admin_consumer_path(consumer), class: 'button-show' %></td>
        <td><%= link_to 'Edit', edit_admin_consumer_path(consumer), class: 'button-edit' %></td>
        <td><%= link_to 'Destroy', admin_consumer_path(consumer), method: :delete, data: { confirm: 'Are you sure?' }, class: 'button-destroy' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Consumer', new_admin_consumer_path, class: 'button-create' %>

app/views/admin/consumers/new.html.erb
<h1>New Consumer</h1>

<%= simple_form_for(@consumer, :url => { :controller => "consumers", :action => "create" },) do |f| %>
  <%= render 'partials/model_errors', resource: @user %>
  <%= f.input :username %>
  <%= f.input :email %>  
  <%= f.input :password %>
  <%= f.input :last_name %>
  <%= f.input :first_name %>
  <%= f.button :submit, 'Save Consumer', class: 'button-create' %>
<% end %>

<%= link_to 'Back to List of Consumers', admin_consumers_path(:admin) %>

app/views/admin/consumers/show.html.erb
<h3>Consumer#<%= @consumer.id %>: <%= @consumer.email %></h3>

<p><strong>Name: </strong><%= @consumer.fullname %></p>

<%= link_to 'Edit Consumer Info', edit_admin_consumer_path(@consumer) %> |
<%= link_to 'Go to Consumers List', admin_consumers_path %>

<%= render 'partials/jobs_month', resource: @consumer, events: @consumer.consumer_jobs, view: :consumer %>
<%= render 'partials/jobs_table', resource: @consumer, events: @consumer.consumer_jobs, view: :consumer %>
<%= render 'partials/jobs_action', resource: @consumer, events: @consumer.consumer_jobs, view: :consumer %>