config/routes.rb
Rails.application.routes.draw do

  root to: "public/pages#home"
  
  devise_for :users
  
  devise_scope :user do
    get 'login'  => 'users/sessions#new',     as: "login"  # published url
    get 'logout' => 'users/sessions#destroy', as: "logout" # published url
  end
    
  namespace :public do
    get 'home' => 'pages#home'
    get 'dash' => 'pages#dashboard'
  end
  
  namespace :admin do
    get 'dashboard' => 'dashboard#show'
    resources :jobs
    resources :users
    resources :customers
    resources :consumers
    resources :interpreters
  end
  
  namespace :customer do
    get 'dashboard' => 'dashboard#show'
    resources :jobs
  end
  
  namespace :consumer do
    get 'dashboard' => 'dashboard#show'
    resources :jobs
  end
  
  namespace :interpreter do
    get 'dashboard' => 'dashboard#show'
    resources :jobs
  end
  
end

app/views/admin/partials/_jobs_action.html.erb
<h3>Jobs (Action View)</h3>
<div class="table-responsive">
<table class="table">
  <thead>
    <tr>
      <th>Job#</th>
      <th>State</th>
      <th>Consumer</th>
      <th>Interpreter</th>
      <th>When</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% events.each do |job| %>
      <tr>
        <td><%= job.id %></td>
        <td><%= job.state.to_s.capitalize %></td>
        <td><%= job.consumer.username %></td>
        <td><%= job.interpreter.email %></td>
        <td><%= job.when %></td>
        <td><%= job.description %></td>
        <td><%= link_to 'Show', show_job_path(job,:admin), class: 'button-show' %></td>
        <td><%= link_to 'Edit', edit_job_path(job,:admin), class: 'button-edit' %></td>
        <td><%= link_to 'Destroy',  jobs_path(job,:admin), method: :delete, data: { confirm: 'Are you sure?' }, class: 'button-destroy' %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/admin/partials/_jobs_month.html.erb
<h3>Jobs (Month View)</h3>
<div class='calendar job-calendar'>
<%= month_calendar events: events do |date,jobs| %>
	<%= date.strftime("%d") %>
	<% jobs.each do |job| %>
    <div>
		<%= link_to "Job##{job.id}", job %>
    </div>
  <% end %>
<% end %>
</div>

app/views/admin/partials/_jobs_table.html.erb
<h3>Jobs (List View)</h3>
<div class="table-responsive">
<table class="table">
  <thead>
    <tr>
      <th>Job#</th>
      <th>State</th>
	  <% if view != :interpreter %>
	  	<th>Interpreter</th>
	  <% end %>
	  <% if view != :consumer %>
	  	<th>Consumer</th>
	  <% end %>
      <th>When</th>
      <th>Description</th>
    </tr>
  </thead>

  <tbody>
    <% events.each do |job| %>
      <tr>
        <td><%= job.id %></td>
        <td><%= job.state.to_s.capitalize %></td>
		<% if view != :interpreter %>
			  <td><%= job.interpreter.username %></td>
		<% end %>
		<% if view != :consumer %>
			  <td><%= job.consumer.fullname %></td>
		<% end %>
        <td><%= job.when %></td>
        <td><%= job.description %></td>
      </tr>
    <% end %>
  </tbody>
</table>